package oleg.sopilnyak.persistence.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import javax.persistence.*;

/**
 * Persistence Model base type ith permanent-id
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(of = "permanentId")
@MappedSuperclass
public abstract class AbstractEntity{
    // unique id generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "permanent_id")
    public Long permanentId;
}